sonar.projectKey=jdgut_curso-cicd-entrega-final-front
sonar.organization=jdgut
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js
sonar.exclusions=node_modules/**, dist/**, public/**, coverage/**, playwright-report/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts, src/vite-env.d.ts, **/*.config.ts